language: go

go:
  - 1.x

services:
  - docker

script:
  - make test docker-build
  - docker run --detach --name ifconfig --publish 7570:7570 --ip 172.17.0.90 samuelkadolph/ifconfig
  - sleep 3
  - curl http://172.17.0.90:7570 | grep "172.17.0.1"
  - docker kill ifconfig
